Feature/implement architecture for financial transactions
bycza-zagroda/track-expenses-app-backend pull request #100
Opened 2022-12-29 22:32 UTC by DawidStuzynski

2022-12-30 00:26 UTC, dawciobiel approved these changes
Looks good to me,
**Maybe** you should add annotation as well, i.e: `@Validated` on `FinancialTransactionService`.

2022-12-30 00:37 UTC, MackowiakPiotr submitted a review, later dismissed
Looks good to me

2022-12-30 15:28 UTC, dawciobiel requested changes
Changes required

2022-12-30 15:28 UTC, dawciobiel commented on src/main/java/pl/byczazagroda/trackexpensesappbackend/model/Wallet.java
> +    private List<FinancialTransaction> financialTransactions;
Please rename the name of `financialTransactions` -> `financialTransactionList`

2022-12-31 16:10 UTC, DawidStuzynski commented on src/main/java/pl/byczazagroda/trackexpensesappbackend/dto/FinancialTransactionDTO.java
> +public record FinancialTransactionDTO(Long id, FinancialTransactionType transactionType, BigDecimal amount,
Changes applied

2023-01-03 10:22 UTC, odzio33 approved these changes
After modify some object name looks good.

2023-01-06 12:04 UTC, odzio33 approved these changes
Looks good for me

2023-01-06 12:32 UTC, mirekgab approved these changes

2023-01-07 09:59 UTC, dawciobiel approved these changes
Looks good for me

2023-01-07 10:00 UTC, merged