Feature/as a user i want to add my transaction to my wallet
bycza-zagroda/track-expenses-app-backend pull request #112
Opened 2023-01-14 15:34 UTC by MackowiakPiotr

2023-01-16 21:55 UTC, odzio33 commented on src/main/java/pl/byczazagroda/trackexpensesappbackend/controller/FinancialTransactionController.java
> +import org.springframework.web.bind.annotation.*;
the wildcard import approach has advantages, but its usage can cause problems in certain situations

please turn off Wildcard imports (https://intellij-support.jetbrains.com/hc/en-us/community/posts/206203659-Turn-off-Wildcard-imports-)

2023-01-16 23:20 UTC, odzio33 commented on src/main/java/pl/byczazagroda/trackexpensesappbackend/controller/FinancialTransactionController.java
>  @RequestMapping("api/transactions/")
please remove last backslash from @RequestMapping("api/transactions/")

2023-01-16 23:28 UTC, odzio33 commented on src/main/java/pl/byczazagroda/trackexpensesappbackend/dto/CreateFinancialTransactionDTO.java
> +public record CreateFinancialTransactionDTO(@Min(1) @NotNull Long walletId, @DecimalMin("0.0") BigDecimal amount,
Please refactor annotation `@DecimalMin("0.0")` to `@DecimalMin("0")`
Please add annotation `@Digits("13,2")`

2023-01-16 23:34 UTC, odzio33 requested changes
changes required

2023-01-17 12:31 UTC, DawidStuzynski commented on src/main/java/pl/byczazagroda/trackexpensesappbackend/service/FinancialTransactionServiceImpl.java
> +        financialTransaction.setDescription(createFinancialTransactionDTO.description());
I think that using @builder would be better

2023-01-21 14:55 UTC, odzio33 requested changes
Changes required

2023-01-21 14:55 UTC, odzio33 commented on src/main/java/pl/byczazagroda/trackexpensesappbackend/dto/CreateFinancialTransactionDTO.java
> +                                            String description, FinancialTransactionType financialTransactionType) {
Please add validation for Enum (FinancialTransactionType ) type

2023-01-22 23:11 UTC, odzio33 approved these changes
Looks good for me

2023-01-22 23:11 UTC, dawciobiel approved these changes
Looks good for me

2023-01-23 23:24 UTC, dawciobiel approved these changes
Looks goods for me

2023-01-24 00:00 UTC, odzio33 approved these changes
Looks good for me

2023-01-24 00:01 UTC, merged