refactor: refactor method getFinancialTransactionByWalletId in Financ…
bycza-zagroda/track-expenses-app-backend pull request #118
Opened 2023-01-24 17:56 UTC by MackowiakPiotr

2023-01-25 10:30 UTC, DawidStuzynski commented on src/main/java/pl/byczazagroda/trackexpensesappbackend/service/FinancialTransactionServiceImpl.java
> +            return null;
I think that better solution would be to return an empty list

2023-01-25 10:31 UTC, DawidStuzynski requested changes
Request changes

2023-01-25 18:03 UTC, dawciobiel approved these changes
Looks good for me

2023-01-25 18:14 UTC, dawciobiel approved these changes
Looks good for me

2023-01-25 18:32 UTC, dawciobiel requested changes
Request changes

2023-01-25 18:32 UTC, dawciobiel commented on src/main/java/pl/byczazagroda/trackexpensesappbackend/service/FinancialTransactionServiceImpl.java
> +        if (financialTransactionsList.isEmpty()) {
Please remove if-then part of the code at all.

2023-01-25 21:51 UTC, dawciobiel requested changes
Request changes

2023-01-25 21:52 UTC, DawidStuzynski submitted a review, later dismissed
Looks good for me

2023-01-27 12:38 UTC, dawciobiel submitted a review, later dismissed
Looks good for me

2023-02-07 23:36 UTC, odzio33 approved these changes
Looks good for me

2023-02-07 23:37 UTC, dawciobiel approved these changes
Looks good for me

2023-02-07 23:37 UTC, merged