add date to financial trasaction - dev profile
bycza-zagroda/track-expenses-app-backend pull request #125
Opened 2023-01-29 22:23 UTC by Iwona007

2023-01-30 19:59 UTC, mirekgab approved these changes

2023-02-01 22:42 UTC, dawciobiel requested changes
Changes required

2023-02-01 22:42 UTC, dawciobiel commented on src/main/resources/db/changelog/data/financialTransaction.csv
> +1,1,INCOME,15000,2022-02-19T09:47:52.595721658,""
`"`  `"` is treated as a String and not as EMPTY_STRING.
It is possible by SQL but it's not possible by Liquibase.
So this line is not needed.
However, this is not a problem. The front-end, when it finds a NULL value - that is, the user did not provide a description value - will insert the EMPTY_STRING value as `"` `"`.

2023-02-07 21:38 UTC, dawciobiel approved these changes
Looks good for me.

2023-02-07 21:39 UTC, dawciobiel approved these changes
Looks good or me

2023-02-07 21:40 UTC, merged