refactor: Refactor method findById, checking for exceptions before ma…
bycza-zagroda/track-expenses-app-backend pull request #130
Opened 2023-01-31 08:05 UTC by MackowiakPiotr

2023-01-31 08:12 UTC, dawciobiel requested changes
Changes required

2023-01-31 08:12 UTC, dawciobiel commented on src/main/java/pl/byczazagroda/trackexpensesappbackend/service/FinancialTransactionServiceImpl.java
> +        return financialTransactionModelMapper.mapFinancialTransactionEntityToFinancialTransactionDTO(financialTransaction);
And with proper code formatting:
```java
    @Override
    public FinancialTransactionDTO findById(@Min(1) @NotNull Long id) {
        FinancialTransaction financialTransaction = financialTransactionRepository.findById(id)
                .orElseThrow(() -> new AppRuntimeException(ErrorCode.FT001,
                String.format("Financial transaction with id: %d not found", id)));

        return financialTransactionModelMapper.mapFinancialTransactionEntityToFinancialTransactionDTO(financialTransaction);
    }
```

or
```java
    @Override
    public FinancialTransactionDTO findById(@Min(1) @NotNull Long id) {
        FinancialTransaction financialTransaction = financialTransactionRepository.findById(id)
                .orElseThrow(() -> new AppRuntimeException(ErrorCode.FT001,
                String.format("Financial transaction with id: %d not found", id)));
        return financialTransactionModelMapper.mapFinancialTransactionEntityToFinancialTransactionDTO(financialTransaction);
    }
```

2023-01-31 08:46 UTC, dawciobiel approved these changes
Looks good for me

2023-02-05 20:40 UTC, odzio33 approved these changes
Looks good for me

2023-02-05 20:51 UTC, merged