financial transaction category creation
bycza-zagroda/track-expenses-app-backend pull request #173
Opened 2023-03-05 22:26 UTC by zetxdev

2023-03-05 22:37 UTC, dawciobiel reviewed
I removed two no need files.

2023-03-09 01:45 UTC, dawciobiel requested changes
Changes required

2023-03-09 01:45 UTC, dawciobiel commented on src/main/java/pl/byczazagroda/trackexpensesappbackend/service/FinancialTransactionCategoryServiceImpl.java
> +@RequiredArgsConstructor
It's a good idea to add annotations in alphabetical order. This way, in every class or class method, it always looks the same.

2023-03-09 01:45 UTC, dawciobiel commented on src/main/java/pl/byczazagroda/trackexpensesappbackend/service/FinancialTransactionCategoryServiceImpl.java
> +    private final FinancialTransactionCategoryModelMapper financialTransactionCategoryModelMapper;
One blank line required between declaration of class fields.

2023-03-09 01:45 UTC, dawciobiel commented on src/main/java/pl/byczazagroda/trackexpensesappbackend/controller/FinancialTransactionCategoryController.java
> +            @Valid @RequestBody FinancialTransactionCategoryCreateDTO financialTransactionCategoryCreateDTO) {
When you are using annotation `@Valid` then `@Validated` on the class is necessary as well.
Anyway please remove `@Valid` from this method and add it to the service method instead. As well please add `@Validated` to the service class.

2023-03-09 01:45 UTC, dawciobiel commented on src/main/java/pl/byczazagroda/trackexpensesappbackend/service/FinancialTransactionCategoryServiceImpl.java
> +    public FinancialTransactionCategoryDTO createFinancialTransactionCategory(
Please add the `@Valid` annotation to this method.

2023-03-09 01:45 UTC, dawciobiel commented on src/main/java/pl/byczazagroda/trackexpensesappbackend/service/FinancialTransactionCategoryServiceImpl.java
> +    public FinancialTransactionCategoryDTO createFinancialTransactionCategory(
The shorter version of Your code:

```java
public FinancialTransactionCategoryDTO createFinancialTransactionCategory(@Valid FinancialTransactionCategoryCreateDTO dto) {
			
	FinancialTransactionCategory entityToSave = new FinancialTransactionCategory(dto.name(), dto.type());
	FinancialTransactionCategory savedEntity = financialTransactionCategoryRepository.save(entityToSave);
			
	return financialTransactionCategoryModelMapper.mapFinancialTransactionCategoryEntityToFinancialTransactionCategoryDTO(savedEntity);
}
```

2023-03-09 01:45 UTC, dawciobiel commented on src/test/java/pl/byczazagroda/trackexpensesappbackend/service/FinancialTransactionCategoryServiceImplTest.java
> +    public static final long ID_1L = 1L;
A blank line between class fields is recommended

2023-03-11 13:48 UTC, dawciobiel approved these changes
Looks good for me

2023-03-14 21:28 UTC, odzio33 requested changes
Changes require

2023-03-14 21:28 UTC, odzio33 commented on src/main/java/pl/byczazagroda/trackexpensesappbackend/exception/ErrorCode.java
> -
Please restore this empty line becouse it was between two diff error codes

2023-03-14 23:32 UTC, dawciobiel submitted a review, later dismissed
Looks good to me.

2023-03-14 23:35 UTC, odzio33 submitted a review, later dismissed
Looks good for me

2023-03-14 23:50 UTC, odzio33 approved these changes
Looks good for me

2023-03-14 23:51 UTC, dawciobiel submitted a review, later dismissed
Looks good for me.

2023-03-15 00:15 UTC, odzio33 approved these changes
Looks good for me

2023-03-15 00:21 UTC, dawciobiel requested changes
changes required.

2023-03-15 00:56 UTC, odzio33 approved these changes
Looks good for me

2023-03-15 01:09 UTC, dawciobiel approved these changes
Looks good to me.

2023-03-15 01:10 UTC, merged