integration test for get Financial Transactions By Wallet ID #183
bycza-zagroda/track-expenses-app-backend pull request #186
Opened 2023-03-11 12:19 UTC by poneciak57

done:
- test when wallet exists and has financial transaction connected

remains:
- test when wallet does not exist

2023-03-11 14:19 UTC, poneciak57 commented
second test that checks when wallet id is incorrect fails because of the issue #163

2023-03-11 15:16 UTC, dawciobiel requested changes
Changes required

2023-03-11 15:16 UTC, dawciobiel commented on src/test/java/pl/byczazagroda/trackexpensesappbackend/integration/GetFinancialTransactionByWalletIdTest.java
> +    private Wallet createTestWallet() {
**This method has a declaration:**
```java
    private Wallet createTestWallet() {
```

**And this one:**
```java
     public void clearDb(){
```
**Why is the formatting of the code in them different?**

2023-03-11 15:16 UTC, dawciobiel commented on src/test/java/pl/byczazagroda/trackexpensesappbackend/integration/GetFinancialTransactionByWalletIdTest.java
> +    public void clearDb(){
Think (I'm sure) name of the method is wrong. 
It is:
```java
clearDb
```

It should be:
```java
clearDB
```

Link:
[What Does Database (DB) Mean?](https://www.techopedia.com/definition/1185/database-db)

2023-03-25 14:24 UTC, DawidStuzynski commented on src/test/java/pl/byczazagroda/trackexpensesappbackend/integration/GetFinancialTransactionByWalletIdTest.java
> +    @Test
Please add also @DisplayName with proper description

2023-03-25 16:03 UTC, dawciobiel requested changes
changes required

2023-03-28 21:41 UTC, odzio33 submitted a review, later dismissed
Looks good for me

2023-04-05 11:37 UTC, dawciobiel submitted a review, later dismissed
Changes required

2023-04-05 11:37 UTC, dawciobiel commented on src/test/java/pl/byczazagroda/trackexpensesappbackend/integration/GetFinancialTransactionByWalletIdTest.java
> +import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
Please don't use asterisk `*` when importing!

2023-04-05 11:37 UTC, dawciobiel commented on src/test/java/pl/byczazagroda/trackexpensesappbackend/integration/GetFinancialTransactionByWalletIdTest.java
> +import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
Please don't use asterisk `*` when importing!

2023-04-05 11:37 UTC, dawciobiel commented on src/test/java/pl/byczazagroda/trackexpensesappbackend/integration/GetFinancialTransactionByWalletIdTest.java
> +                .andExpect(jsonPath("$.[0].date").value(financialTransaction.getDate().toString()));
Add one blank line before using assertions.

2023-04-05 11:37 UTC, dawciobiel commented on src/test/java/pl/byczazagroda/trackexpensesappbackend/integration/GetFinancialTransactionByWalletIdTest.java
> +        Assertions.assertEquals(0, financialTransactionRepository.count());
Add one blank line before using assertions.

2023-04-12 21:11 UTC, mirekgab commented on src/test/java/pl/byczazagroda/trackexpensesappbackend/integration/GetFinancialTransactionByWalletIdTest.java
Rename the file to GetFinancialTransactionByWalletIdIT.java (IT suffix - integration test).

2023-04-12 21:12 UTC, mirekgab commented on src/test/java/pl/byczazagroda/trackexpensesappbackend/integration/GetFinancialTransactionByWalletIdTest.java
> +                .date(Instant.ofEpochMilli(0L))
```suggestion
                .date(Instant.ofEpochSecond(1L))
```
The minimum timestamp value is 1 second.

2023-04-13 08:12 UTC, mirekgab commented
Please update your branch and resolve conflicts.

2023-04-15 10:32 UTC, mirekgab commented on src/test/java/pl/byczazagroda/trackexpensesappbackend/integration/GetFinancialTransactionByWalletIdIT.java
> +
From a business point of view, the status returned in the response body is important. Add a check that this status has the correct value W003.
```json
{
    "status": "W003",
    "message": "WALLET_NOT_FOUND",
    "description": "Wallet with id: 38 does not exist",
    "statusCode": 404
}
```

2023-04-15 10:32 UTC, mirekgab commented on src/main/resources/db/dbchangelog-test.yaml
Did you change anything in this file?

2023-04-15 20:02 UTC, poneciak57 commented on src/main/resources/db/dbchangelog-test.yaml
yes i changed it at the begining and now i only merged changes from main while resolving conflict

2023-04-17 15:38 UTC, mirekgab approved these changes
I think it looks good.

2023-04-17 21:27 UTC, odzio33 approved these changes
Looks good to me

2023-04-17 21:27 UTC, merged

2023-04-18 18:08 UTC, Krisu93 reviewed
Looks good for me