Test/rest get all wallets
bycza-zagroda/track-expenses-app-backend pull request #198
Opened 2023-03-20 16:12 UTC by McSymilian

preview version, server response with code 200 but empty body

2023-03-25 13:47 UTC, DawidStuzynski requested changes
It should be integration test, at this point of time service is mocked. Please look at WalletTestIT class

2023-04-26 17:33 UTC, dawciobiel submitted a review, later dismissed
Request changes

2023-05-01 22:24 UTC, mirekgab approved these changes

2023-05-03 06:36 UTC, mirekgab approved these changes

2023-05-03 09:43 UTC, odzio33 approved these changes
Looks good for me

2023-05-03 09:45 UTC, merged