test/integration_test_for_update_Wallet
bycza-zagroda/track-expenses-app-backend pull request #199
Opened 2023-03-20 22:37 UTC by MackowiakPiotr

feature: add line - db/changelog/003-create-table-financial_transactions.yaml
test: add integration test for update wallet

2023-03-25 13:23 UTC, DawidStuzynski commented on src/test/java/pl/byczazagroda/trackexpensesappbackend/integration/TestUpdateWallet.java
> +
To the endpoint we should pass DTO object instead of entity.

2023-03-25 13:26 UTC, DawidStuzynski commented on src/test/java/pl/byczazagroda/trackexpensesappbackend/integration/TestUpdateWallet.java
> +                .content(objectMapper.writeValueAsString(updatedWallet)));
To the endpoint we should pass DTO object instead of entity.

2023-03-25 13:27 UTC, DawidStuzynski requested changes
Request changes

2023-03-29 05:45 UTC, dawciobiel requested changes
Request changes

2023-03-29 14:25 UTC, dawciobiel requested changes
changes required

2023-03-29 22:13 UTC, MackowiakPiotr commented on src/test/java/pl/byczazagroda/trackexpensesappbackend/integration/TestUpdateWallet.java
> +                .andDo(print());
done

2023-03-29 23:36 UTC, dawciobiel requested changes
Request changes

2023-03-29 23:36 UTC, dawciobiel commented on src/test/java/pl/byczazagroda/trackexpensesappbackend/integration/TestUpdateWallet.java
> +    void testUpdateWallet_whenWalletIdIsIncorrect_thenReturnErrorResponse() throws Exception {
Please add `@DisplayName` annotation on your every test method.

2023-04-01 13:27 UTC, DawidStuzynski approved these changes
Looks good for me

2023-04-04 06:27 UTC, odzio33 approved these changes
Looks good for me

2023-04-04 06:30 UTC, dawciobiel approved these changes
Looks good to me

2023-04-04 06:30 UTC, merged