Integration test for delete transaction by ID #181
bycza-zagroda/track-expenses-app-backend pull request #218
Opened 2023-04-23 20:04 UTC by Dharakkkk

2023-04-25 08:48 UTC, mirekgab commented on src/test/java/pl/byczazagroda/trackexpensesappbackend/integration/DeleteTransactionByIdTest.java
> +    public void testDeleteFinancialTransactionById_whenDeletedFinancialTransactionWithExistingId_thenReturnDeletedSuccesfully()
You don't need the `public` modifier for a test method.

2023-04-25 08:48 UTC, mirekgab commented on src/test/java/pl/byczazagroda/trackexpensesappbackend/integration/DeleteTransactionByIdTest.java
> +public class DeleteTransactionByIdTest extends BaseIntegrationTestIT {
You don't need `public` modifier for the class.

2023-04-25 08:48 UTC, mirekgab commented on src/test/java/pl/byczazagroda/trackexpensesappbackend/integration/DeleteTransactionByIdTest.java
> +                .accept(MediaType.APPLICATION_JSON)).andExpect(MockMvcResultMatchers.status().isNotFound()).andReturn();
Do we need the `andReturn()` method here?

2023-04-25 14:11 UTC, dawciobiel requested changes
Changes required

2023-04-25 14:11 UTC, dawciobiel commented on src/test/java/pl/byczazagroda/trackexpensesappbackend/integration/DeleteTransactionByIdTest.java
> +
Improve code formatting

2023-04-25 14:11 UTC, dawciobiel commented on src/test/java/pl/byczazagroda/trackexpensesappbackend/integration/DeleteTransactionByIdTest.java
> +
Improve code formatting

2023-04-26 11:47 UTC, dawciobiel commented
L:47 not needed blank line - and there should not be.
Same with L:73 - there are two blank lines, and there should be only one

2023-04-26 17:07 UTC, mirekgab approved these changes

2023-04-26 17:34 UTC, merged

2023-04-26 17:58 UTC, dawciobiel reviewed
Looks good to me