Integration test/creating financial trasnaction
bycza-zagroda/track-expenses-app-backend pull request #221
Opened 2023-04-27 11:06 UTC by zetxdev

integration test for creating Financial Transaction #180

2023-04-28 12:29 UTC, dawciobiel approved these changes
Looks good to me

2023-04-29 17:25 UTC, dawciobiel requested changes
Request changes

2023-04-29 17:25 UTC, dawciobiel commented on src/test/java/pl/byczazagroda/trackexpensesappbackend/integration/CreateFinancialTransactionIT.java
> +    private static BigDecimal TRANSACTION_AMOUNT_LIMIT = new BigDecimal("999999999999999.99");
```suggestion
   /**
   The maximum value for the `amount` parameter is described as:
   {@link  pl.byczazagroda.trackexpensesappbackend.dto.FinancialTransactionCreateDTO  FinancialTransactionCreateDTO}
   */
    private static final BigDecimal MAX_ALLOWED_TRANSACTION_AMOUNT = new BigDecimal("10000000000000.00");
```

2023-05-03 15:26 UTC, dawciobiel approved these changes
Looks good for me.
GetAllWalletsIT - this file should be already on origin `develop`.

2023-05-03 22:58 UTC, odzio33 approved these changes
Looks good for me

2023-05-03 22:58 UTC, merged