bugfix/update financial transaction
bycza-zagroda/track-expenses-app-backend pull request #223
Opened 2023-04-30 15:30 UTC by sylvvester

2023-04-30 22:29 UTC, Iwona007 submitted a review, later dismissed

2023-05-01 14:28 UTC, dawciobiel requested changes
Changes required

2023-05-01 14:28 UTC, dawciobiel commented on src/main/java/pl/byczazagroda/trackexpensesappbackend/service/FinancialTransactionServiceImpl.java
> +        if (uDTO.categoryId() != null) {
Please replace it with:

```java
Long categoryId = uDTO.categoryId();

        if (categoryId != null) {
            FinancialTransactionCategory financialTransactionCategory = financialTransactionCategoryRepository.findById(categoryId)
```

2023-05-01 14:36 UTC, mirekgab commented on src/main/java/pl/byczazagroda/trackexpensesappbackend/service/FinancialTransactionServiceImpl.java
> +            entity.setFinancialTransactionCategory(financialTransactionCategory);
Let's consider a situation where uDTO.type() != financialTransactionCategory.getType()?
Shouldn't an exception be thrown?

2023-05-01 14:36 UTC, mirekgab commented on src/main/java/pl/byczazagroda/trackexpensesappbackend/service/FinancialTransactionServiceImpl.java
> +        if (uDTO.categoryId() != null) {
Consider a situation where entity.categoryId!=null and uDTO.categoryId==null. Will the categoryId be updated?

2023-05-06 17:37 UTC, Iwona007 approved these changes

2023-05-06 17:37 UTC, dawciobiel approved these changes
Looks good to me

2023-05-06 17:37 UTC, merged