test: add unit test for updating financial transaction #215
bycza-zagroda/track-expenses-app-backend pull request #224
Opened 2023-04-30 21:53 UTC by sylvvester

- test for updating financial transaction with invalid id in FinancialTransactionService
- test for updating a financial transaction with valid parameters in FinancialTransactionService

2023-05-03 07:10 UTC, mirekgab commented
This should be merged after PR 223 merging.

2023-05-06 17:51 UTC, dawciobiel requested changes
Request changes

2023-05-06 17:51 UTC, dawciobiel commented on src/test/java/pl/byczazagroda/trackexpensesappbackend/service/FinancialTransactionServiceImplTest.java
> +        return new FinancialTransactionUpdateDTO(TEN,DATE_NOW, DESCRIPTION, EXPENSE,null);
fix code formatting

2023-05-06 17:51 UTC, dawciobiel commented on src/test/java/pl/byczazagroda/trackexpensesappbackend/service/FinancialTransactionServiceImplTest.java
> +        );
You can add one empty line before block assertion code

2023-05-06 17:51 UTC, dawciobiel commented on src/test/java/pl/byczazagroda/trackexpensesappbackend/service/FinancialTransactionServiceImplTest.java
> +        assertEquals(ErrorCode.FT001.getBusinessMessage(), exception.getBusinessMessage());
You can add one empty line before verifying the block code - just like you did in `shouldUpdateFinancialTransactionWhenValidParametersAreGiven()` test method.

2023-05-06 18:48 UTC, dawciobiel approved these changes
Looks good to me

2023-05-06 18:50 UTC, Iwona007 approved these changes

2023-05-06 18:51 UTC, merged