enhancement/Add constraints on columns in database tables #206
bycza-zagroda/track-expenses-app-backend pull request #228
Opened 2023-05-05 20:05 UTC by zetxdev

Add constraints on columns in database tables #206

due to the fact that the most desired functionality to resolve this issue (addCheckConstraint) is included in paid licenses I proposed workaround with executing sql script from external file which is invoked from liquibase version management file anyway.

2023-05-05 21:16 UTC, mirekgab requested changes

2023-05-05 21:16 UTC, mirekgab commented on src/main/resources/db/changelog/constrains.sql
> +ALTER TABLE financial_transactions ADD CHECK (amount > 0);
```suggestion
ALTER TABLE financial_transactions ADD CONSTRAINT financial_transaction_check_amount CHECK (amount > 0);
```
Add constraint name.

2023-05-05 22:20 UTC, mirekgab approved these changes

2023-05-06 05:58 UTC, mirekgab submitted a review, later dismissed

2023-05-06 15:01 UTC, dawciobiel requested changes
Request changes

2023-05-06 15:01 UTC, dawciobiel commented on src/main/resources/db/changelog/008-add-constraints-on-columns-in-database-tables.yaml
> +            path: db/changelog/constrains.sql
Please reneme name of thisfile to:
`008-add-constraints-on-columns-in-database-tables.sql`

2023-05-06 17:46 UTC, dawciobiel submitted a review, later dismissed
Looks good to me

2023-05-06 18:39 UTC, dawciobiel approved these changes
Looks good to me

2023-05-06 18:41 UTC, Iwona007 approved these changes

2023-05-06 18:42 UTC, merged