Bugfix/in financial transaction dto include null values #239
bycza-zagroda/track-expenses-app-backend pull request #240
Opened 2023-05-14 13:35 UTC by sylvvester

2023-05-14 16:06 UTC, mirekgab approved these changes

2023-05-14 18:44 UTC, poneciak57 requested changes

2023-05-14 18:44 UTC, poneciak57 commented on src/main/java/pl/byczazagroda/trackexpensesappbackend/dto/FinancialTransactionDTO.java
> +                                      FinancialTransactionType type, Instant date, @JsonInclude Long categoryId) {
`@JsonInclude` -> `@JsonInclude(JsonInclude.Include.ALWAYS)` 
That should work you can check the discord fo further info

2023-05-15 07:14 UTC, mirekgab approved these changes

2023-05-16 14:53 UTC, poneciak57 approved these changes
Looks good to me

2023-05-16 14:55 UTC, merged