feature/235-implement user registeration
bycza-zagroda/track-expenses-app-backend pull request #252
Opened 2023-05-25 21:17 UTC by Dharakkkk

1. Implemented the UserService and UserServiceImpl:
   - Added methods for user registration, password hashing, email validation, and password validation.
   - Added necessary checks for existing email, password strength, and email format.

2. Updated UserRepository:
   - Added the existsByEmail method to check for existing users.

3. Created integration tests for the implemented functionality in UserServiceImplTest:
   - Tests for successful user registration, handling existing email, invalid email, and weak password.

4. Integrated user registration into AuthController:
   - Added a POST endpoint for user registration.

5. Added required dependencies to pom.xml:
   - Included the spring-security-crypto dependency for password hashing."

#### Checklist template for LEADERS

&#x2611; | &#x2610;

&#x2610; New code is covered with tests and coverage requirements are met.
&#x2610; Build is not failing.
&#x2610; All tests are passing.
&#x2610; All conflicts are resolved and the branch is rebased on top of the up-to-date parent branch.
&#x2610; All issue requirements are implemented.
&#x2610; At least two reviewers are assigned.
&#x2610; The Pull request is linked to the related issue.
&#x2610; Correct branch name. Convention [https://github.com/bycza-zagroda/track-expenses-app-documentation/blob/develop/githubwork/GITHUB_WORK.md]
&#x2610; Correct unit test name - suffix 'Test' in the end.
&#x2610; Correct integration test name - suffix 'IT' in the end.
&#x2610; Positive and negative test paths have been implemented.

2023-05-26 05:32 UTC, poneciak57 requested changes
Missing proper code formatting

2023-05-26 05:32 UTC, poneciak57 commented on src/main/java/pl/byczazagroda/trackexpensesappbackend/controller/AuthController.java
> +private final UserService userService;
Code formating: Enter between class proprties and methods

2023-05-26 05:32 UTC, poneciak57 commented on src/main/java/pl/byczazagroda/trackexpensesappbackend/repository/UserRepository.java
> +    boolean existsByEmail(String email);
Code formating: Enter between class proprties and methods

2023-05-26 05:32 UTC, poneciak57 commented on src/main/java/pl/byczazagroda/trackexpensesappbackend/service/UserService.java
> +    void registerUser(@Valid AuthRegisterDTO authRegisterDTO);
Code formating: Enter between class proprties and methods

2023-05-26 05:32 UTC, poneciak57 commented on src/main/java/pl/byczazagroda/trackexpensesappbackend/service/UserServiceImpl.java
> +public class UserServiceImpl implements UserService{
Code formating: Enter between class proprties and methods format the whole class

2023-05-26 05:32 UTC, poneciak57 commented on src/test/java/pl/byczazagroda/trackexpensesappbackend/service/UserServiceImplTest.java
> +    @Mock
Code formating: Enter between class proprties and methods format the whole class

2023-05-26 05:38 UTC, poneciak57 requested changes
Requested changes

2023-05-26 05:38 UTC, poneciak57 commented on src/main/java/pl/byczazagroda/trackexpensesappbackend/service/UserServiceImpl.java
> +            throw new IllegalArgumentException("A user with the same email already exists");
You should change the exception to the `AppRuntimeException` according to our error handling strategy u can refer to other services. It applies to whole service.

2023-05-26 17:51 UTC, poneciak57 requested changes
Requested changes

2023-05-26 17:51 UTC, poneciak57 commented on src/test/java/pl/byczazagroda/trackexpensesappbackend/integration/UserServiceImplIT.java
> +public class UserServiceImplIT {
Should be `UserRegisterationIT`

2023-05-26 17:51 UTC, poneciak57 commented on src/test/java/pl/byczazagroda/trackexpensesappbackend/integration/UserServiceImplIT.java
> +        String url = "/api/auth/register";
url should be `private static final String` class field

2023-05-26 17:51 UTC, poneciak57 commented on src/test/java/pl/byczazagroda/trackexpensesappbackend/integration/UserServiceImplIT.java
> +    @Test
Tests should have description

2023-05-26 17:51 UTC, poneciak57 commented on src/test/java/pl/byczazagroda/trackexpensesappbackend/integration/UserServiceImplIT.java
> +    public void testRegisterUser() {
we have naming convention for tests like
`test<what your are testing>_when<case like "when user already exists">_then<what should happen>`

2023-05-26 17:51 UTC, poneciak57 commented on src/test/java/pl/byczazagroda/trackexpensesappbackend/service/UserServiceImplTest.java
> +    @Mock
still not resolved

2023-05-29 18:41 UTC, poneciak57 requested changes
Asterix imports and tests methods names need to be fixed

2023-05-29 18:41 UTC, poneciak57 commented on src/test/java/pl/byczazagroda/trackexpensesappbackend/integration/UserRegistrationIT.java
> +import static org.junit.jupiter.api.Assertions.*;
do not use asterix imports, change to static imports

2023-05-29 18:41 UTC, poneciak57 commented on src/test/java/pl/byczazagroda/trackexpensesappbackend/service/UserServiceImplTest.java
> +import static org.junit.Assert.*;
Do not use asterix imports, change to static imports

2023-05-29 18:41 UTC, poneciak57 commented on src/test/java/pl/byczazagroda/trackexpensesappbackend/service/UserServiceImplTest.java
> +    public void testHashPassword_WhenPasswordIsValid_ThenReturnHashed() {
like in your integration tests When and Then should be lowercase so
from `testHashPassword_WhenPasswordIsValid_ThenReturnHashed`
to `testHashPassword_whenPasswordIsValid_thenReturnHashed`
applies to whole class

2023-05-29 18:41 UTC, poneciak57 commented on src/test/java/pl/byczazagroda/trackexpensesappbackend/service/UserServiceImplTest.java
> +import org.mockito.*;
Do not use asterix imports, change to static imports

2023-05-29 18:50 UTC, poneciak57 submitted a review, later dismissed
Looks good to me

2023-05-29 22:13 UTC, dawciobiel requested changes
Request changes

2023-05-29 22:13 UTC, dawciobiel commented on src/test/java/pl/byczazagroda/trackexpensesappbackend/service/UserServiceImplTest.java
> +    }
Please add one empty line after this bracket

2023-05-30 13:55 UTC, dawciobiel requested changes
changes required

2023-05-31 00:21 UTC, dawciobiel requested changes
Changes required

2023-06-06 07:56 UTC, dawciobiel requested changes
Request changes

2023-06-06 07:56 UTC, dawciobiel commented on src/main/java/pl/byczazagroda/trackexpensesappbackend/service/UserServiceImpl.java
> +        if (userRepository.existsByEmail(authRegisterDTO.email())) {
I think it's better to verify the e-mail address beforehand, and only then refer to the repository to check it.

2023-06-06 07:56 UTC, dawciobiel commented on src/main/java/pl/byczazagroda/trackexpensesappbackend/service/UserServiceImpl.java
> +        String emailRegex = "^[A-Za-z0-9+_.-]+@(.+)$";
Variables still have different names and serve the same purpose.
L:60 `emailRegex `
and L:68 `pattern`

2023-06-06 07:56 UTC, dawciobiel commented on src/test/java/pl/byczazagroda/trackexpensesappbackend/integration/UserRegistrationIT.java
> +                .userName("User Bolek")
Here you got:
```java
.userName("User Bolek")
```
but on line L:26 you got another user name.
```java
    private static final AuthRegisterDTO REGISTER_DTO =
            new AuthRegisterDTO("user@server.com", "User123@", "User_Bolek");
```

2023-06-06 10:27 UTC, dawciobiel approved these changes
Looks good to me

2023-06-06 17:09 UTC, poneciak57 approved these changes
Looks good to me

2023-06-06 17:10 UTC, merged