Fix test case for finding wallets by name pattern and update repository methods (#251)
bycza-zagroda/track-expenses-app-backend pull request #261
Opened 2023-06-09 15:01 UTC by sylvvester

…ry methods

#### Checklist template for LEADERS

&#x2611; | &#x2610;

&#x2610; New code is covered with tests and coverage requirements are met.
&#x2610; Build is not failing.
&#x2610; All tests are passing.
&#x2610; All conflicts are resolved and the branch is rebased on top of the up-to-date parent branch.
&#x2610; All issue requirements are implemented.
&#x2610; At least two reviewers are assigned.
&#x2610; The Pull request is linked to the related issue.
&#x2610; Correct branch name. Convention [https://github.com/bycza-zagroda/track-expenses-app-documentation/blob/develop/githubwork/GITHUB_WORK.md]
&#x2610; Correct unit test name - suffix 'Test' in the end.
&#x2610; Correct integration test name - suffix 'IT' in the end.
&#x2610; Positive and negative test paths have been implemented.

2023-06-09 15:53 UTC, mirekgab requested changes

2023-06-09 15:53 UTC, mirekgab commented on src/test/java/pl/byczazagroda/trackexpensesappbackend/service/WalletGetServiceImplTest.java
>          List<Wallet> walletList = createListOfWalletsByName("Family wallet", "Common Wallet", "Smith Family Wallet");
At least one wallet name must contains 'family' lower case.

2023-06-09 15:53 UTC, mirekgab commented on src/test/java/pl/byczazagroda/trackexpensesappbackend/service/WalletGetServiceImplTest.java
> +                        .filter(walletDTO -> Objects.equals(wallet.getName(), walletDTO.name()))
```suggestion
                        .filter(wallet -> wallet.getName().toUpperCase().contains(walletNameSearched.toUpperCase()))
```
In this method, we should compare the names case-insensitive.

2023-06-09 16:20 UTC, mirekgab commented on src/test/java/pl/byczazagroda/trackexpensesappbackend/service/WalletGetServiceImplTest.java
> +                        .filter(walletDTO -> Objects.equals(wallet.getName(), walletDTO.name()))
Please fix tests in `FindAllWalletsByNameCaseSensitiveIT` class.
In the method `createListTestWallets` add another wallet 
```java
        final Wallet fifthWallet = Wallet.builder()
                .user(user)
                .creationDate(Instant.now())
                .name("Wallet Test")
                .build();
```

2023-06-16 16:27 UTC, mirekgab approved these changes

2023-06-18 21:34 UTC, Iwona007 approved these changes

2023-06-18 21:37 UTC, dawciobiel approved these changes
Looks good to me

2023-06-18 21:37 UTC, merged