task/271-Implement error codes and DTO converter
bycza-zagroda/track-expenses-app-backend pull request #275
Opened 2023-06-25 20:11 UTC by dawciobiel

-add: error codes 401 Unauthorized, 403 forbidden
-add: DTO to JSON converter

#### Checklist template for LEADERS

&#x2611; | &#x2610;

&#x2610; New code is covered with tests and coverage requirements are met.
&#x2610; Build is not failing.
&#x2610; All tests are passing.
&#x2610; All conflicts are resolved and the branch is rebased on top of the up-to-date parent branch.
&#x2610; All issue requirements are implemented.
&#x2610; At least two reviewers are assigned.
&#x2610; The Pull request is linked to the related issue.
&#x2610; Correct branch name. Convention [https://github.com/bycza-zagroda/track-expenses-app-documentation/blob/develop/githubwork/GITHUB_WORK.md]
&#x2610; Correct unit test name - suffix 'Test' in the end.
&#x2610; Correct integration test name - suffix 'IT' in the end.
&#x2610; Positive and negative test paths have been implemented.

2023-06-25 22:03 UTC, Iwona007 requested changes
Fantastic work. However please consider my suggestion.

2023-06-25 22:03 UTC, Iwona007 commented on src/main/java/pl/byczazagroda/trackexpensesappbackend/config/WebSecurityConfig.java
>      private final String secret;
Please add above secret this annotation: @Value("${jwt.secret}")

2023-06-25 22:03 UTC, Iwona007 commented on src/main/java/pl/byczazagroda/trackexpensesappbackend/config/WebSecurityConfig.java
Please delete constructor. Annotation @Requiredargsconstructor resolve this. Moreover we don't have to modify constructor everytime when additional parameter is added.

2023-06-26 19:19 UTC, mirekgab approved these changes

2023-06-26 22:26 UTC, Iwona007 approved these changes

2023-06-26 22:27 UTC, merged