feat/Implemented user login
bycza-zagroda/track-expenses-app-backend pull request #276
Opened 2023-06-26 09:55 UTC by poneciak57

#### Checklist template for LEADERS

&#x2611; | &#x2610;

&#x2610; New code is covered with tests and coverage requirements are met.
&#x2610; Build is not failing.
&#x2610; All tests are passing.
&#x2610; All conflicts are resolved and the branch is rebased on top of the up-to-date parent branch.
&#x2610; All issue requirements are implemented.
&#x2610; At least two reviewers are assigned.
&#x2610; The Pull request is linked to the related issue.
&#x2610; Correct branch name. Convention [https://github.com/bycza-zagroda/track-expenses-app-documentation/blob/develop/githubwork/GITHUB_WORK.md]
&#x2610; Correct unit test name - suffix 'Test' in the end.
&#x2610; Correct integration test name - suffix 'IT' in the end.
&#x2610; Positive and negative test paths have been implemented.

2023-06-26 19:25 UTC, dawciobiel approved these changes
Looks good to me

2023-06-26 19:26 UTC, dawciobiel requested changes
Request changes

2023-06-27 05:04 UTC, dawciobiel submitted a review, later dismissed
LGTM

2023-06-27 06:43 UTC, dawciobiel submitted a review, later dismissed
LGTM

2023-06-27 17:00 UTC, mirekgab requested changes

2023-06-27 17:00 UTC, mirekgab commented on src/test/java/pl/byczazagroda/trackexpensesappbackend/integration/UserRegistrationIT.java
> +@Import(WebSecurityConfig.class)
In an integration test, you don't need to import the configuration explicitly.

2023-06-27 17:23 UTC, Iwona007 requested changes
Request changes

2023-06-27 17:28 UTC, Iwona007 requested changes
Request changes

2023-06-27 17:28 UTC, Iwona007 commented on src/test/java/pl/byczazagroda/trackexpensesappbackend/integration/UserLoginIT.java
> +
Why you don't extends BaseIntegrationTestIT?

2023-06-28 06:10 UTC, mirekgab submitted a review, later dismissed

2023-06-28 19:09 UTC, Iwona007 approved these changes

2023-06-28 19:10 UTC, mirekgab approved these changes

2023-06-28 19:10 UTC, merged