Feature/update financial transaction category controller #257
bycza-zagroda/track-expenses-app-backend pull request #278
Opened 2023-07-08 11:30 UTC by sylvvester

#### Checklist template for LEADERS

&#x2611; | &#x2610;

&#x2610; New code is covered with tests and coverage requirements are met.
&#x2610; Build is not failing.
&#x2610; All tests are passing.
&#x2610; All conflicts are resolved and the branch is rebased on top of the up-to-date parent branch.
&#x2610; All issue requirements are implemented.
&#x2610; At least two reviewers are assigned.
&#x2610; The Pull request is linked to the related issue.
&#x2610; Correct branch name. Convention [https://github.com/bycza-zagroda/track-expenses-app-documentation/blob/develop/githubwork/GITHUB_WORK.md]
&#x2610; Correct unit test name - suffix 'Test' in the end.
&#x2610; Correct integration test name - suffix 'IT' in the end.
&#x2610; Positive and negative test paths have been implemented.

2023-07-08 11:59 UTC, dawciobiel requested changes
Request changes

2023-07-08 11:59 UTC, dawciobiel commented on src/main/java/pl/byczazagroda/trackexpensesappbackend/controller/FinancialTransactionCategoryController.java
>          return new ResponseEntity<>(financialTransactionCategoryDTOList, HttpStatus.OK);
One empty line before this one please - just like you got it in L:44

2023-07-08 11:59 UTC, dawciobiel commented on src/main/java/pl/byczazagroda/trackexpensesappbackend/controller/FinancialTransactionCategoryController.java
>          return new ResponseEntity<>(financialTransactionCategoryDTO, HttpStatus.CREATED);
One empty line before this one please - just like you got it in L:44

2023-07-08 11:59 UTC, dawciobiel commented on src/main/java/pl/byczazagroda/trackexpensesappbackend/controller/FinancialTransactionCategoryController.java
>          return new ResponseEntity<>(financialTransactionCategoryDTO, HttpStatus.OK);
One empty line before this one please - just like you got it in L:44

2023-07-08 11:59 UTC, dawciobiel commented on src/main/java/pl/byczazagroda/trackexpensesappbackend/controller/FinancialTransactionCategoryController.java
>          return new ResponseEntity<>(HttpStatus.NO_CONTENT);
One empty line before this one please - just like you got it in L:44

2023-07-08 14:27 UTC, dawciobiel submitted a review, later dismissed
LGTM

2023-07-10 17:42 UTC, dawciobiel approved these changes
LGTM

2023-07-10 18:20 UTC, mirekgab approved these changes

2023-07-10 18:21 UTC, merged