Implement Refresh Token functionality and tests
bycza-zagroda/track-expenses-app-backend pull request #279
Opened 2023-07-17 00:34 UTC by Dharakkkk

This commit includes the implementation of refresh tokens functionality in the auth controller, as well as associated tests. Here are the detailed notes on the changes made:

Implementation of the POST /api/auth/refresh endpoint in the auth controller. This function retrieves the refresh token from the request, validates it, and creates a new access token and refresh token. The new refresh token is then added to the response as a cookie.

Implementation of a series of unit tests for the aforementioned function. These tests cover different scenarios such as the case when both the access token and the refresh token are valid, absence of the refresh token, incorrect access token, incorrect refresh token, and the case when the access token has expired.

Moving the RefreshTokenTest tests to the 'controller' package, since these tests are focused on the behavior of the auth controller.

Updating the names of the tests to be more descriptive and adding @DisplayName annotations to each test to make it easier to understand what each test does.

This commit aims to provide refresh tokens functionality, which is essential for the security and convenience of users.

#### Checklist template for LEADERS

&#x2611; | &#x2610;

&#x2610; New code is covered with tests and coverage requirements are met.
&#x2610; Build is not failing.
&#x2610; All tests are passing.
&#x2610; All conflicts are resolved and the branch is rebased on top of the up-to-date parent branch.
&#x2610; All issue requirements are implemented.
&#x2610; At least two reviewers are assigned.
&#x2610; The Pull request is linked to the related issue.
&#x2610; Correct branch name. Convention [https://github.com/bycza-zagroda/track-expenses-app-documentation/blob/develop/githubwork/GITHUB_WORK.md]
&#x2610; Correct unit test name - suffix 'Test' in the end.
&#x2610; Correct integration test name - suffix 'IT' in the end.
&#x2610; Positive and negative test paths have been implemented.

2023-07-17 07:10 UTC, poneciak57 requested changes
Requested changes

2023-07-17 07:10 UTC, poneciak57 commented on src/main/java/pl/byczazagroda/trackexpensesappbackend/config/WebSecurityConfig.java
> +                        .antMatchers("/api/auth/refresh").authenticated()
user should be able to reach refresh endpoint when he is unauthenticated, thats the whole point of refreshing
users token expired -> user refreshes the token -> user is able to continue using api

2023-07-17 07:10 UTC, poneciak57 commented on src/main/java/pl/byczazagroda/trackexpensesappbackend/controller/AuthController.java
> +    public ResponseEntity<AuthAccessTokenDTO> refreshToken(@CookieValue(name = "refresh_token", required = false) String refreshToken, HttpServletRequest request, HttpServletResponse response) {
refresh token is required

2023-07-17 07:10 UTC, poneciak57 commented on src/main/java/pl/byczazagroda/trackexpensesappbackend/controller/AuthController.java
> +        if (userService.validateToken(accessToken) && userService.validateToken(refreshToken)) {
access token should have valid signature but can be expired in that case
on the other hand refresh token should have valid signature as well as cannot be expired

2023-07-17 07:10 UTC, poneciak57 commented on src/main/java/pl/byczazagroda/trackexpensesappbackend/controller/AuthController.java
> +        }
I think the whole logic of this endpoint should be in service

2023-07-17 07:10 UTC, poneciak57 commented on src/test/java/pl/byczazagroda/trackexpensesappbackend/controller/RefreshTokenTest.java
> +    void refreshTokenWithExpiredAccessToken_thenReturnUnauthorized() throws Exception {
as i mentioned earlier user should be able to refresh expired access token in particular

2023-07-19 12:42 UTC, dawciobiel approved these changes
LGTM

2023-07-19 18:30 UTC, dawciobiel commented on src/main/java/pl/byczazagroda/trackexpensesappbackend/service/UserServiceImpl.java
> +            throw new AppRuntimeException(ErrorCode.U004,
Please create a new error code in `ErrorCodes` - for example:
```java
S003("S003", "REFRESH_TOKEN_NOT_VALID", 403); // 401, 403 or other proper HTTP code.
```
**Links**
https://en.wikipedia.org/wiki/List_of_HTTP_status_codes

2023-07-19 18:30 UTC, dawciobiel commented on src/main/java/pl/byczazagroda/trackexpensesappbackend/service/UserServiceImpl.java
> +        if(!validateTokenSignature(accessTokenWithoutBearer)) {
```suggestion
        if (!validateTokenSignature(accessTokenWithoutBearer)) {
```

2023-07-25 17:18 UTC, poneciak57 approved these changes
Looks good to me

2023-07-25 21:49 UTC, dawciobiel approved these changes
LGTM

2023-07-25 21:49 UTC, merged