Created Integration Test
bycza-zagroda/track-expenses-app-backend pull request #282
Opened 2023-07-30 20:29 UTC by Dharakkkk

#### Checklist template for LEADERS

&#x2611; | &#x2610;

&#x2610; New code is covered with tests and coverage requirements are met.
&#x2610; Build is not failing.
&#x2610; All tests are passing.
&#x2610; All conflicts are resolved and the branch is rebased on top of the up-to-date parent branch.
&#x2610; All issue requirements are implemented.
&#x2610; At least two reviewers are assigned.
&#x2610; The Pull request is linked to the related issue.
&#x2610; Correct branch name. Convention [https://github.com/bycza-zagroda/track-expenses-app-documentation/blob/develop/githubwork/GITHUB_WORK.md]
&#x2610; Correct unit test name - suffix 'Test' in the end.
&#x2610; Correct integration test name - suffix 'IT' in the end.
&#x2610; Positive and negative test paths have been implemented.

2023-07-31 15:42 UTC, dawciobiel approved these changes
LGTM

2023-08-04 06:16 UTC, poneciak57 requested changes
changes required

2023-08-04 06:16 UTC, poneciak57 commented on src/main/java/pl/byczazagroda/trackexpensesappbackend/repository/FinancialTransactionCategoryRepository.java
> +    @Query("SELECT CASE WHEN COUNT(c) > 0 THEN true ELSE false END FROM FinancialTransactionCategory c WHERE c.id = :id and c.user.id = :userId")
CASE seems redundant in here, try to replace it with something like this:
```sql
SELECT COUNT(c) > 0 as result
FROM FinancialTransactionCategory c
WHERE c.id = :id AND c.user.id = :userId;
```

2023-08-07 18:19 UTC, dawciobiel requested changes
Fix the code formatting and I'll accept it.

2023-08-07 18:19 UTC, dawciobiel commented on src/test/java/pl/byczazagroda/trackexpensesappbackend/integration/DeleteFinancialCategoryIT.java
> +        return categoryRepository.save(category);
One empty line can be added above the `return` statement.

2023-08-07 18:19 UTC, dawciobiel commented on src/test/java/pl/byczazagroda/trackexpensesappbackend/integration/DeleteFinancialCategoryIT.java
> +        return userRepository.save(user);
One empty line can be added above the `return` statement.

2023-08-07 18:19 UTC, dawciobiel commented on src/test/java/pl/byczazagroda/trackexpensesappbackend/integration/DeleteFinancialCategoryIT.java
> +    private static final String BEARER = "Bearer ";
```suggestion
    private static final String AUTHORIZATION = "Authorization";

    private static final String BEARER = "Bearer ";
```

2023-08-07 18:19 UTC, dawciobiel commented on src/test/java/pl/byczazagroda/trackexpensesappbackend/integration/DeleteFinancialCategoryIT.java
> +    private final String deleteCategoryUrl = "/api/categories/{id}";
```suggestion
    private final Long nonExistentCategoryId = 999L;

    private final String deleteCategoryUrl = "/api/categories/{id}";
```

2023-08-08 13:23 UTC, dawciobiel approved these changes
LGTM

2023-08-08 18:06 UTC, poneciak57 requested changes

2023-08-08 18:06 UTC, poneciak57 commented on src/main/java/pl/byczazagroda/trackexpensesappbackend/repository/FinancialTransactionCategoryRepository.java
> +    @Query(value = "SELECT COUNT(c) > 0 as result FROM FinancialTransactionCategory c WHERE c.id = :id AND c.user.id = :userId")
```suggestion
    @Query(nativeQuery = false, value = "SELECT COUNT(c) > 0 as result FROM FinancialTransactionCategory c WHERE c.id = :id AND c.user.id = :userId")
```

2023-08-08 18:07 UTC, poneciak57 approved these changes
Looks good to me

2023-08-08 18:08 UTC, dawciobiel approved these changes
LGTM

2023-08-08 18:09 UTC, merged