getting started
bycza-zagroda/track-expenses-app-backend pull request #71
Opened 2022-11-03 21:55 UTC by Krisu93

2022-11-06 21:43 UTC, MateuszBednarczyk commented on src/main/java/pl/byczazagroda/trackexpensesappbackend/controller/WalletController.java
> +import javax.validation.constraints.*;
https://stackoverflow.com/questions/147454/why-is-using-a-wild-card-with-a-java-import-statement-bad

2022-11-06 21:43 UTC, MateuszBednarczyk commented on src/main/java/pl/byczazagroda/trackexpensesappbackend/service/WalletService.java
> +import javax.validation.constraints.*;
You shouldn't import the whole package ``javax.validation.constraints``

2022-11-10 14:31 UTC, dawciobiel requested changes
Request changes.
When you will fix the code, please do update your local working branch with commits from the remote. So you will be able to resolve conflicts (if exist) locally.

2022-11-11 13:49 UTC, dawciobiel approved these changes
Looks good for me.

2022-11-11 14:25 UTC, dawciobiel commented
@Krisu93 Please do update the project with remove `develop`, merge it and then again commit with push to resolve conflicts locally.

2022-11-16 19:08 UTC, dawciobiel commented on src/main/java/pl/byczazagroda/trackexpensesappbackend/service/WalletServiceImpl.java
> +        return getWallets().stream().filter(walletDTO -> walletDTO.name().contains(name)).toList();
For a sane user, there will only be 1-few wallets in the app.
However, your point is correct.

2022-11-16 19:14 UTC, dawciobiel commented on src/test/java/pl/byczazagroda/trackexpensesappbackend/controller/WalletControllerTest.java
> +    @DisplayName("Should return information about all wallets funded by part of a wallet name and http ok status")
Should be:
_It should return information about all wallets indicated by a part of the name and `HttpStatus.OK`_

2022-11-16 19:40 UTC, dawciobiel commented on src/test/java/pl/byczazagroda/trackexpensesappbackend/service/WalletServiceImplTest.java
> +        walletList.forEach(wallet -> given(walletModelMapper.mapWalletEntityToWalletDTO(wallet)).willReturn(walletListDTO.stream().filter(walletDTO -> Objects.equals(wallet.getName(), walletDTO.name(
Create `Wallet` entity list.
On the base of it create `WalletDTO` list.
For `given(walletRepository.findAll())` return list of `Wallet`.
Then find on the result list is any `WalletDTO` that is equals with given `Wallet`.
	To do it compare fields: [`wallet.name`, `walletDTO.name`.]
	
Line #273 is 221 characters long!
Refactoring needed.

2022-11-16 20:01 UTC, dawciobiel requested changes
Changes required.

2022-11-18 18:59 UTC, dawciobiel approved these changes
Looks good for me

2022-11-18 19:16 UTC, purbanski-deftcode approved these changes

2022-11-18 23:18 UTC, dawciobiel approved these changes
Looks good for me

2022-11-18 23:21 UTC, DawidStuzynski approved these changes

2022-11-18 23:22 UTC, DawidStuzynski approved these changes
Looks good for me

2022-11-18 23:55 UTC, MateuszBednarczyk approved these changes

2022-11-18 23:55 UTC, MateuszBednarczyk commented on src/main/java/pl/byczazagroda/trackexpensesappbackend/controller/WalletController.java
> +        List<WalletDTO> walletsDTO = walletService.getAll();
I would like to suggest `walletDTOs`.

2022-11-19 01:20 UTC, dawciobiel approved these changes
Look good for me

2022-11-19 01:20 UTC, merged